### ISSUE TITLE
Panic while panicking after an out-of-bounds index on real-world images

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-jpeg#13]
The attached image triggers the following panic in zune-jpeg:

```
thread '<unnamed>' panicked at 'range end index 13761 out of range for slice of length 13344', library/core/src/slice/index.rs:73:5
```

[138_1.jpg](https://user-images.githubusercontent.com/291257/177017146-23bd5297-c0fb-447a-9ec9-d97e30bf582d.jpg)

The panic seems to occur in all worker threads, and then trigger another panic when propagated to the caller, causing the process to abort.

The code to reproduce it is the same as in https://github.com/etemesi254/zune-jpeg/issues/10

Tested on commit e99e93cafcd63b017311036593482c63cd2bd723 (latest as of this writing)

**Comment by etemesi254** [comment]
Does it report what part isn't working? (IDCT, upsampler,  color conversion)?

**Comment by Shnatsel** [comment]
The failing function appears to be `zune_jpeg::color_convert::scalar::ycbcr_to_grayscale`

**Comment by etemesi254** [comment]
This image is a down-sampled grayscale image. 

Weird because it contains only a Y component, a Y component can't be downsampled... :)

But issue is a wrong image output chunk size issue, fix coming right up.
