### ISSUE TITLE
Fails to decode photos taken by Google Pixel phones

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-jpeg#14]
zune-jpeg seems to fail to decode photos taken by Google Pixel phones. They display correctly in web browsers and my desktop image viewer, as well as `jpeg-decoder` crate.

Sample file demonstrating the issue: [PXL_20220202_150158375](https://user-images.githubusercontent.com/291257/177232018-d5328741-b586-414b-a7b7-eba0c58c9802.jpg)

**Comment by etemesi254** [comment]
Will look into it over the weekend

(Sorry for late reply)

**Comment by Shnatsel** [comment]
No worries! I understand this is a spare time project, and you don't owe me anything.

Besides, I will probably keep finding issues for a while, since real-world JPEGs are so weird and varied. It's unreasonable to expect them to always be fixed promptly, that's just not sustainable for you.

Take as much time as you need, and don't hesitate to ask for help!

**Comment by etemesi254** [comment]
What part was failing on this?

**Comment by Shnatsel** [comment]
Decoding takes a suspiciously short time - as if it's a no-op. I measured 15ms with zune-jpeg vs 800 ms with djpeg, which sounds too good to be true.

I do not have any code handy that would display the images decoded with zune-jpeg (or save them to BMP or anything of the sort), so I cannot check what exactly it displays.

And yes, that photo can be added to the test suite.

**Comment by etemesi254** [comment]
Yep, it is sadly not blazingly fast decode speeds  :-{

IT seems to be skipping a lot of markers. 

Also what would you need for that code to decode and display images, I'm thinking of whipping up such a binary with clap-rs as cmd parser and was wondering what features you might need.

1. I had, similarity checker (in memory) for a start

**Comment by Shnatsel** [comment]
All I need is exporting the image to some lossless format - BMP or PNG. I can rig the similarity checking externally.

I also don't need a fancy argument parser, although you're welcome to use one if you prefer. The code I was using for `image` and conversely `jpeg-decoder` is this:

```rust
use std::error::Error;
use image::io::Reader as ImageReader;

fn main() -> Result<(), Box<dyn Error>> {
    let input = std::env::args().nth(1).unwrap();
    let output = std::env::args().nth(2).unwrap();
    
    let img = ImageReader::open(input)?.decode()?;
    img.save(output)?;
    Ok(())
}
```

That's literally it.
