### ISSUE TITLE
4k JPEG fails to decode with "Bad Huffman Code"

### ISSUE THREAD

**Issue by SludgePhD** [etemesi254/zune-jpeg#25]
[error.jpg.zip](https://github.com/etemesi254/zune-jpeg/files/9742357/error.jpg.zip)

This image (4096x2160 pixels) fails to decode with

> Error: Error decoding huffman values: Bad Huffman Code 0xFFAC, corrupt JPEG

**Comment by SludgePhD** [comment]
In fact it looks like every resolution of my webcam above 1080p causes these sort of errors

**Comment by etemesi254** [comment]
Looking into it.

**Comment by etemesi254** [comment]
Dev branch has a change that fixes the above issue,  pushing to crates.io with the fix will have to wait a little bit.

Test on your side and if it works feel free to close this issue

**Comment by SludgePhD** [comment]
Nice, looks like that fixes it. Thanks!
