### ISSUE TITLE
Valid JPEG fails to decode ("Wrong QT bit set")

### ISSUE THREAD

**Issue by SludgePhD** [etemesi254/zune-jpeg#9]
The following image decodes fine in Firefox, VS Code, and `jpeg-decoder`, but fails to decode with zune-jpeg:

![error](https://user-images.githubusercontent.com/96552222/173155735-9881fdee-b1e6-49a9-8b82-0091402078c3.jpeg)

(it doesn't seem to be able to decode any image output by my webcam, they all produce this error)

**Comment by SludgePhD** [comment]
Forgot to attach the full error:

    Error parsing DQT segment. Reason:Wrong QT bit set,expected value between 0 and 3,found 4

**Comment by etemesi254** [comment]
Hello SludgePhD, the issue was a superfluous error check in the library. Just pushed a change to remove it.

Also could I add the image to the test suite? It has some interesting properties I'd like to ensure continue working in the library.

Also thanks for the heads up.

**Comment by SludgePhD** [comment]
Awesome, works fine now, and it's twice as fast as jpeg-decoder and mozjpeg :tada: 

> Also could I add the image to the test suite?

Sure, go ahead!

**Comment by etemesi254** [comment]
Thanks for the image.

I'd like to keep this issue open until I push a new update to crates.io (in a few days) then it can be closed.
